### ISSUE TITLE
Persistence DefectDojo fails with Exception in logs

### ISSUE THREAD

**Issue by Beastlex** [secureCodeBox/secureCodeBox#1549]
## Your Question

Hello.
After ZAP scan log of container contains:
`
2023-01-11 12:39:01 INFO  DefectDojoPersistenceProvider:25 - Starting DefectDojo persistence provider
2023-01-11 12:39:06 INFO  DefectDojoPersistenceProvider:36 - Downloading Scan Result
2023-01-11 12:39:07 INFO  DefectDojoPersistenceProvider:40 - Uploading Findings to DefectDojo at: http://defect-dojo-new-defectdojo-django.defect-dojo-new
Exception in thread "main" java.lang.IllegalArgumentException: Illegal character(s) in message header value: Token [our admin token here]

        at java.base/sun.net.www.protocol.http.HttpURLConnection.checkMessageHeader(HttpURLConnection.java:585)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.isExternalMessageHeaderAllowed(HttpURLConnection.java:515)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.addRequestProperty(HttpURLConnection.java:3348)
        at org.springframework.http.client.SimpleBufferingClientHttpRequest.lambda$addHeaders$0(SimpleBufferingClientHttpRequest.java:110)
        at java.base/java.util.Map.forEach(Map.java:713)
        at org.springframework.http.client.SimpleBufferingClientHttpRequest.addHeaders(SimpleBufferingClientHttpRequest.java:102)
        at org.springframework.http.client.SimpleBufferingClientHttpRequest.executeInternal(SimpleBufferingClientHttpRequest.java:68)
        at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48)
        at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:66)
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:776)
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:751)
        at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:621)
        at io.securecodebox.persistence.defectdojo.service.GenericDefectDojoService.internalSearch(GenericDefectDojoService.java:172)
        at io.securecodebox.persistence.defectdojo.service.GenericDefectDojoService.search(GenericDefectDojoService.java:188)
        at io.securecodebox.persistence.defectdojo.service.GenericDefectDojoService.searchUnique(GenericDefectDojoService.java:208)
        at io.securecodebox.persistence.strategies.VersionedEngagementsStrategy.run(VersionedEngagementsStrategy.java:82)
        at io.securecodebox.persistence.DefectDojoPersistenceProvider.main(DefectDojoPersistenceProvider.java:43)`

**Comment by Natali-Dubotolkova** [comment]
Yes, I have the same problem.
When trying to download the results after ZAP scanning in secureCodeBox, it writes that 
Exception in thread "main" java.lang.IllegalArgumentException: Illegal character(s) in message header value: Token asasasasa
But the token is exactly correct!

**Comment by J12934** [comment]
Hi,
sorry i haven't come across this issue yet.
Some googling of the error message seems to suggest that this often happens to people who accidentally included new lines in the value of headers. Can you make sure that you didn't accidentally include a new line at the end of the token?

If this doesn't seem to be the case are there any characters in the token which might be considered invalid values in a http header?

**Comment by Beastlex** [comment]
Thanks a lot! Remove 'newline' and it works
