### ISSUE TITLE
DefectDojo Hook fails in Version 4.7.0

### ISSUE THREAD

**Issue by kaz-33** [secureCodeBox/secureCodeBox#2614]
## 🐞 Bug report

i can't create a new report in defectdojo
### Describe the bug

it'look like to this
https://github.com/secureCodeBox/secureCodeBox/issues/2285
As you can see securecodebox, try to create a project,with id=0

### System (persistenceDefectdojo):
```
4.6 -->OK
4.7--> KO
```

### Screenshots / Logs

![image](https://github.com/user-attachments/assets/8e3aa28b-32c3-4ad6-972c-624a991b8dbf)

**Comment by Weltraumschaf** [comment]
Hi @kaz-33,

thanks for submitting this issue. We'll investigate this.

**Comment by J12934** [comment]
I can reproduce this issue.
I'm assuming this is due to the refactorings we did, @Weltraumschaf can you have a look?

**Comment by moxli** [comment]
I can reproduce this after upgrading from 4.5.0 to 4.9.0.

**4.5.0**
```
2024-10-09 08:39:30 INFO  VersionedEngagementsStrategy:248 - Looking for ID of ProductType 'Customer Facing Infrastructure'
2024-10-09 08:39:30 INFO  VersionedEngagementsStrategy:255 - Using ProductType Id: 2
2024-10-09 08:39:31 INFO  VersionedEngagementsStrategy:224 - Creating new Engagement as no matching Engagements could be found.
2024-10-09 08:39:32 INFO  VersionedEngagementsStrategy:154 - Uploaded Scan Report as testID 7374 to DefectDojo
2024-10-09 08:39:32 INFO  VersionedEngagementsStrategy:384 - Waiting for 60 seconds for deduplication to finish before continuing
2024-10-09 08:40:32 INFO  DefectDojoPersistenceProvider:51 - Identified total Number of findings in DefectDojo: 3
2024-10-09 08:40:32 INFO  DefectDojoPersistenceProvider:65 - Overwriting secureCodeBox findings with the findings from DefectDojo.
2024-10-09 08:40:33 INFO  S3Service:25 - Uploading Findings to S3
2024-10-09 08:40:33 INFO  KubernetesService:97 - Updating Scan metadata
2024-10-09 08:40:33 INFO  DefectDojoPersistenceProvider:57 - DefectDojo Persistence Completed

```


**4.9.0**
```
2024-10-09 08:24:17 INFO  VersionedEngagementsStrategy:248 - Looking for ID of ProductType 'Customer Facing Infrastructure'
2024-10-09 08:24:17 INFO  VersionedEngagementsStrategy:251 - ProductType 'Customer Facing Infrastructure' didn't already exists creating now
2024-10-09 08:24:17 ERROR GenericDefectDojoService:152 - Exception while doing a POST request to DefectDojo API: 400 Bad Request: "{"name":["product_ type with this name already exists."],"message":"{'name': [ErrorDetail(string='product_ type with this name already exists.', code='unique')]}"}"
2024-10-09 08:24:17 ERROR DefectDojoPersistenceProvider:30 - Failed to do a POST to DefectDojo API!
io.securecodebox.persistence.defectdojo.exception.PersistenceException: Failed to do a POST to DefectDojo API!
        at io.securecodebox.persistence.defectdojo.service.GenericDefectDojoService.create(GenericDefectDojoService.java:153)
        at io.securecodebox.persistence.strategies.VersionedEngagementsStrategy.lambda$ensureProductTypeExistsForScan$4(VersionedEngagementsStrategy.java:252)
        at java.base/java.util.Optional.orElseGet(Optional.java:364)
        at io.securecodebox.persistence.strategies.VersionedEngagementsStrategy.ensureProductTypeExistsForScan(VersionedEngagementsStrategy.java:250)
        at io.securecodebox.persistence.strategies.VersionedEngagementsStrategy.run(VersionedEngagementsStrategy.java:100)
        at io.securecodebox.persistence.DefectDojoPersistenceProvider.execute(DefectDojoPersistenceProvider.java:50)
        at io.securecodebox.persistence.DefectDojoPersistenceProvider.main(DefectDojoPersistenceProvider.java:28)
Caused by: org.springframework.web.client.HttpClientErrorException$BadRequest: 400 Bad Request: "{"name":["product_ type with this name already exists."],"message":"{'name': [ErrorDetail(string='product_ type with this name already exists.', code='unique')]}"}"
        at org.springframework.web.client.HttpClientErrorException.create(HttpClientErrorException.java:103)
        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:183)
        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:137)
        at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)
        at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:942)
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:891)
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:790)
        at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:672)
        at io.securecodebox.persistence.defectdojo.service.GenericDefectDojoService.create(GenericDefectDojoService.java:145)
        ... 6 more
```

**Comment by Weltraumschaf** [comment]
Update to 3.0.0 temp. disabled: https://github.com/secureCodeBox/secureCodeBox/pull/2746

**Comment by vira-vira** [comment]
Hello Is this issue fixed? I am having the same error :)

**Comment by J12934** [comment]
The issue should be resolved with v4.10.0.

Sorry for the long delay :/

**Comment by Weltraumschaf** [comment]
It is not fixed in HEAD, but we backprted to a working version.

**Comment by kaz-33** [comment]
not fixed in 4.11.0?

**Comment by Weltraumschaf** [comment]
> Fixed in 4.12.0?

It is not fixed in HEAD, but we backprted to a working version.

**Comment by kaz-33** [comment]
just for fun, 
pin version in 4.6.0 OK
pin version in 4.6.1 NOK

**Comment by GeiserX** [comment]
@Weltraumschaf please could you explain your last message? It's not clear to me whether `4.12.0` is working or not, even if its a backport

**Comment by Weltraumschaf** [comment]
> [@Weltraumschaf](https://github.com/Weltraumschaf) please could you explain your last message? It's not clear to me whether `4.12.0` is working or not, even if it's a backport

Yes, it should works because we used a prior working version of [defectdojo-client-java](https://github.com/secureCodeBox/defectdojo-client-java). But in defectdojo-client-java the bug is still not fixed.

**Comment by kaz-33** [comment]
no working from my site on 4.12.0, only on 4.6.0.

**Comment by Weltraumschaf** [comment]
> no working from my site on 4.12.0, only on 4.6.0.

Same error?

**Comment by Weltraumschaf** [comment]
We verified this. We use the latest DefecDojo Hook in our production environment. It works :-)

The origin [bug](https://github.com/secureCodeBox/defectdojo-client-java/pull/130) is still open, but does not affect current versions as of v4.10.0

**Comment by kaz-33** [comment]
thx, i will check with 4.13.0

**Comment by kaz-33** [comment]
fix for me in 4.13.0, thx guys!
