### ISSUE TITLE
Failed to parse trivy-k8s output Unexpected attribute 'Packages' on resource-item

### ISSUE THREAD

**Issue by paraddise** [secureCodeBox/secureCodeBox#2689]
### Describe the bug
After successful trivy k8s scan parser fails.

### Steps To Reproduce
deploy trivy scan type from docs
```shell
helm upgrade --install trivy oci://ghcr.io/securecodebox/helm/trivy --version 4.9.0
```
Run trivy-k8s scan
```shell
scbctl scan trivy-k8s -- --db-repository my-registry/aquasecurity/trivy-db --java-db-repository my-registry/aquasecurity/trivy-java-db --checks-bundle-repository my-registry/aquasecurity/trivy-checks --debug --include-namespaces infra-securecodebox --severity CRITICAL        
```
### Expected behavior
```
Scan completed and result get parsed.
```

### System (please complete the following information):

secureCodeBox: 4.9.0
```shell
$ kubectl version
Client Version: v1.29.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.4
```
### Screenshots / Logs
Logs from trivy parser

```
Starting Parser
(node:1) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Fetching result file
Fetched result file
Parser failed with error:
Error: Unexpected attribute 'Packages' on resource-item
    at parseK8sScanResultResource (/home/app/parser-wrapper/parser/parser.js:136:14)
    at /home/app/parser-wrapper/parser/parser.js:117:70
    at Array.flatMap (<anonymous>)
    at /home/app/parser-wrapper/parser/parser.js:117:44
    at new Promise (<anonymous>)
    at parseK8sScanResults (/home/app/parser-wrapper/parser/parser.js:104:10)
    at parse (/home/app/parser-wrapper/parser/parser.js:22:18)
    at main (/home/app/parser-wrapper/parser-wrapper.js:154:22)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
```

**Comment by Weltraumschaf** [comment]
Hi @paraddise,

thanks for submitting this issue. We'll investigate this.

**Comment by BorisShek** [comment]
I have also encountered this while working with trivy k8s parser. My temporary workaround was to add "Packages" to the expectedAttributes list in [L133](https://github.com/secureCodeBox/secureCodeBox/blob/main/scanners/trivy/parser/parser.js#L133)
