### ISSUE TITLE
Issue when pushing findings with Persistent Hook to DefectDojo

### ISSUE THREAD

**Issue by vira-vira** [secureCodeBox/secureCodeBox#2755]
### Discussed in https://github.com/secureCodeBox/secureCodeBox/discussions/2754

<div type='discussions-op-text'>

<sup>Originally posted by **vira-vira** November 12, 2024</sup>
Hello everyone!!

Thanks for working on this project! I believe is amazing! I have an issue that I am not able to fix it. Maybe you can help me.
I created a cluster on GCP, everything is working properly, I created a namespace called defectdojo and another one where I have the scanners. I installed defect dojo in the defectdojo namespace and the persistent hook on the scanners.
The issue I have is the following:
When I create a new scan, the persistent hook detects this, and send the findings to DefectDojo. When I see the UI, I am able to see that DefectDojo Creates a product, it also creates all the fields I defined with annotations, but the findings list is empty and I should have some. 
I tried several things without success, for example I increase the resources assigned to defect dojo, I add more memory, I also changed the ` defectdojo.syncFindingsBack=false`.
Here are some logs from the persistent hook:
```
ERROR GenericDefectDojoService:152 - Exception while doing a POST request to DefectDojo API: 400 Bad Request: "{"name":["product with this name already exists."],"message":"{'name': [ErrorDetail(string='product with this name already exists.', code='unique')]}"}"
ERROR DefectDojoPersistenceProvider:30 - Failed to do a POST to DefectDojo API!"
io.securecodebox.persistence.defectdojo.exception.PersistenceException: Failed to do a POST to DefectDojo API!
	at io.securecodebox.persistence.defectdojo.service.GenericDefectDojoService.create(GenericDefectDojoService.java:153)
	at io.securecodebox.persistence.strategies.VersionedEngagementsStrategy.lambda$ensureProductExistsForScan$5(VersionedEngagementsStrategy.java:276)
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at io.securecodebox.persistence.strategies.VersionedEngagementsStrategy.ensureProductExistsForScan(VersionedEngagementsStrategy.java:274)
	at io.securecodebox.persistence.strategies.VersionedEngagementsStrategy.run(VersionedEngagementsStrategy.java:101)
	at io.securecodebox.persistence.DefectDojoPersistenceProvider.execute(DefectDojoPersistenceProvider.java:50)
	at io.securecodebox.persistence.DefectDojoPersistenceProvider.main(DefectDojoPersistenceProvider.java:28)
Caused by: org.springframework.web.client.HttpClientErrorException$BadRequest: 400 Bad Request: "{"name":["product with this name already exists."],"message":"{'name': [ErrorDetail(string='product with this name already exists.', code='unique')]}"}"
	at org.springframework.web.client.HttpClientErrorException.create(HttpClientErrorException.java:103)
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:183)
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:137)
	at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:942)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:891)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:790)
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:672)
	at io.securecodebox.persistence.defectdojo.service.GenericDefectDojoService.create(GenericDefectDojoService.java:145)
	... 6 more
```

Could you help me to understand why I am not able to see any finding on defect dojo? 

Thanks and regards,

Sergio</div>

**Comment by J12934** [comment]
Should be resovled, see #2614
