### ISSUE TITLE
DefectDojo persistence provider unable to use new SecureCodeBox Findings Importer

### ISSUE THREAD

**Issue by EndPositive** [secureCodeBox/secureCodeBox#490]
### Describe the bug
The DefectDojo persistence provider is unable to import scan results using the new (unreleased) secureCodeBox parser. This is because the code expects a corresponding test type (i.e. "SecureCodeBox Findings Importer". As (briefly) explained in [#4431](https://github.com/DefectDojo/django-DefectDojo/pull/4431), the test types are no longer updated for new importers.

This can be seen when manually importing scan results with the DefectDojo UI. Only a Scan Type has to be provided, which is derived from the available importers (see [here](https://github.com/secureCodeBox/django-DefectDojo/blob/8d030f03860ff5deea464590dfeaf727b484a49c/dojo/api_v2/serializers.py#L1102-L1103)). The same details have to be provided to the ImportScanSerializer in DefectDojo (API).

Due to the fact that SecureCodeBox's java wrapper/client is not up to date ([#6](https://github.com/secureCodeBox/defectdojo-client-java/issues/6)), we can't currently fix this issue in this project. However, when the wrapper is updated, we will have to update the persistence-provider. This needs to be updated in order for the new parser to function.

If you need any more info, send me a msg on slack!

### Steps To Reproduce
1. Enable generic parser:

https://github.com/secureCodeBox/secureCodeBox/blob/7367c124ffb165140f38d36e70a941070d354408/hooks/persistence-defectdojo/src/main/java/io/securecodebox/persistence/util/ScanNameMapping.java#L46-L48

2. Setup SecureCodeBox + locally built persistence provider ^^.
3. Run an instance of [parser-SCB](https://github.com/secureCodeBox/django-DefectDojo/tree/parser-SCB)
4. Start a random scan.

```
Exception in thread "main" io.securecodebox.persistence.exceptions.DefectDojoPersistenceException: Could not find test type 'SecureCodeBox Findings Import' in DefectDojo API. DefectDojo might be running in an unsupported version.
	at io.securecodebox.persistence.strategies.VersionedEngagementsStrategy.lambda$createTest$7(VersionedEngagementsStrategy.java:242)
	at java.base/java.util.Optional.orElseThrow(Optional.java:408)
	at io.securecodebox.persistence.strategies.VersionedEngagementsStrategy.createTest(VersionedEngagementsStrategy.java:242)
	at io.securecodebox.persistence.strategies.VersionedEngagementsStrategy.run(VersionedEngagementsStrategy.java:83)
	at io.securecodebox.persistence.DefectDojoPersistenceProvider.main(DefectDojoPersistenceProvider.java:58)
```

### Additional context
Check out [#6](https://github.com/secureCodeBox/defectdojo-client-java/issues/6) in the defectdojo wrapper.

**Comment by EndPositive** [comment]
Looks like Johannes his PR works wonderfully! If we won't use a separate secureCodeBox findings importer, I'll close the issue. I'll keep [#6](https://github.com/secureCodeBox/defectdojo-client-java/issues/6) open for now in case Johannes still wants to update the wrapper.
